
pipeline {
    agent any

    stages {       
        stage("Build") {
            agent {
                docker { 
                    image 'node:18-alpine'
                    reuseNode true          // share workspace across agents
                    }
            }
            steps {
                sh """
                    echo "Running Build Stage"
                    ls -la
                    node --version
                    npm --version
                    npm ci         # install dependencies in package.json (ci version)
                    npm run build
                    ls -la build
                """
            }
        }

        stage("Tests"){
            parallel{                   // everything in this block is to be run in parallel
                stage("Unit Test") {
                    agent {
                        docker { 
                            image 'node:18-alpine'
                            reuseNode true          // share workspace across agents
                            }
                    }
                    steps {
                        sh """
                            echo "Running Basic Test Stage"
                            ls -la
                            test -f build/index.html
                            npm test
                        """
                    }
                }
                stage("E2E Test") {
                    agent {
                        docker { 
                            image 'mcr.microsoft.com/playwright:v1.39.0-jammy'
                            reuseNode true          // share workspace across agents
                            }
                    }
                    steps {
                        sh """
                            echo "Running E2E Testing Stage"
                            npm install serve                   # Install serve locally into: node_modules/.bin/serve
                            node_modules/.bin/serve -s build &  # spin up webserver in background (TCP/3000) using the contents of the build directory
                            sleep 10                            # wait for webserver to come up
                            npx playwright test                 # this starts the playwright tests 
                        """
                    }
                }
            }
        }
    }
    post {
        always{
            junit "jest-results/junit.xml" // publish the junit test report - using output of junit test stanza
        }
    }
}
