pipeline {
    agent any

    stages {       
        stage("Build") {
            agent {
                docker { 
                    image 'node:18-alpine'
                    reuseNode true          // share workspace across agents
                    }
            }
            steps {
                sh """
                    ls -la
                    node --version
                    npm --version
                    npm ci         # install dependencies in package.json (ci version)
                    npm run build
                    ls -la build
                """
            }
        }
    }
}
